/* Study Hub — a fixed, expandable 100-question master bank.
   LocalStorage is isolated behind load/save helpers so a database adapter can replace it later. */
const CATS = {
  lines: "Characters' Lines — The Odyssey", oxymorons: "Oxymoronic Expressions — The Bread of Salt",
  stories: "5 Selected Short Stories", history: "History of Greek Literature",
  gods: "Greek Gods & Goddesses", qualities: "Analysis — Qualities of Greek Literature",
  works: "Multiple Choice — Iliad, Odyssey & Oedipus"
};
const qbank = [];
const add = (id, category, topic, prompt, choices, answer, explanation, difficulty="Normal", kind="Multiple Choice") => qbank.push({id,category,topic,prompt,choices,answer,explanation,difficulty,kind});
const mc = (id,cat,topic,prompt,choices,answer,why,diff) => add(id,cat,topic,prompt,choices,answer,why,diff||["Easy","Normal","Hard"][qbank.length%3]);

// PART I: 15 scene/dialogue identifications. Paraphrases avoid edition-specific quotation wording.
const L=CATS.lines;
mc("OD-LINE-001",L,"Odysseus","In a paraphrase of his introduction to Alcinous, the speaker says: “I am Odysseus, son of Laertes, known for my cunning.” Who is speaking?",["Telemachus","Odysseus","Alcinous","Eumaeus"],"Odysseus","He identifies himself to Alcinous and the Phaeacian court.");
mc("OD-LINE-002",L,"Penelope","In a paraphrase, who tells the suitors: “I will choose when this burial cloth is finished,” while secretly unweaving it at night?",["Helen","Nausicaa","Penelope","Arete"],"Penelope","The weaving trick delays the suitors while she hopes for Odysseus's return.");
mc("OD-LINE-003",L,"Athena","Which goddess, often disguised as Mentor, advises Telemachus: “Go seek news of your father”?",["Hera","Athena","Artemis","Aphrodite"],"Athena","Athena uses disguises and advice to help Odysseus's household.");
mc("OD-LINE-004",L,"Telemachus","At the Ithacan assembly, which young man protests that suitors are consuming his father's home and pressuring his mother?",["Laertes","Telemachus","Eurylochus","Peisistratus"],"Telemachus","His journey and growing confidence form the opening coming-of-age episode.");
mc("OD-LINE-005",L,"Zeus","In a paraphrase, which god says: “Mortals blame the gods, though their own choices bring them pain”?",["Poseidon","Hermes","Zeus","Apollo"],"Zeus","The poem repeatedly explores both divine influence and human responsibility.");
mc("OD-LINE-006",L,"Poseidon","Which god's response to the report “Odysseus blinded my son” is to make the hero's sea journey harder?",["Apollo","Poseidon","Ares","Hephaestus"],"Poseidon","Polyphemus is Poseidon's son, so his father obstructs Odysseus's voyage.");
mc("OD-LINE-007",L,"Calypso","Which nymph tells Odysseus, in paraphrase: “Stay with me and you may escape old age and death”?",["Circe","Calypso","Arete","Ino"],"Calypso","She detains him for years, but he longs to return to Ithaca.");
mc("OD-LINE-008",L,"Circe","Which enchantress says, in paraphrase: “Your crew is safe now; I will tell you how to reach the Underworld”?",["Calypso","Circe","Nausicaa","Athena"],"Circe","The enchantress first threatens the crew, then becomes their ally.");
mc("OD-LINE-009",L,"Alcinous","A Phaeacian king promises a ship to carry his guest home. Who is this king?",["Nestor","Alcinous","Menelaus","Agamemnon"],"Alcinous","He hosts Odysseus and provides a ship to Ithaca.");
mc("OD-LINE-010",L,"Polyphemus","Which Cyclops cries that “Nobody” is attacking him after a stranger gives that name?",["Antinous","Polyphemus","Tiresias","Proteus"],"Polyphemus","Odysseus escapes by blinding him and hiding beneath the sheep.");
mc("OD-LINE-011",L,"Eumaeus","Who is the loyal swineherd who shelters the disguised Odysseus?",["Eumaeus","Philoetius","Eurycleia","Melanthius"],"Eumaeus","He remains faithful to the household and welcomes the stranger.");
mc("OD-LINE-012",L,"Eurycleia","Who recognizes Odysseus by the scar while washing his feet, but is told to keep quiet?",["Penelope","Eurycleia","Arete","Melantho"],"Eurycleia","The old nurse recognizes the scar from a boar hunt.");
mc("OD-LINE-013",L,"Nausicaa","Which princess finds Odysseus by the river and directs him toward her parents' palace?",["Helen","Nausicaa","Calypso","Circe"],"Nausicaa","She shows him how to approach Queen Arete and King Alcinous.");
mc("OD-LINE-014",L,"Tiresias","Which blind Theban prophet gives Odysseus instructions in the land of the dead?",["Tiresias","Nestor","Proteus","Agamemnon"],"Tiresias","His prophecy explains the dangers ahead and Odysseus's eventual return.");
mc("OD-LINE-015",L,"Argos","Which character is Odysseus's old dog, who recognizes him and dies after seeing him again?",["Argos","Eumaeus","Laertes","Elpenor"],"Argos","The neglected dog recognizes his master even in disguise.");

// PART II: 10 oxymoron meaning questions. Only “awfully good” is identified as the class example from the prompt.
const O=CATS.oxymorons;
mc("BOS-OXY-001",O,"Awfully good","In the class example “awfully good,” what does the expression mean?",["Very bad","Surprisingly or exceptionally good","Good only in appearance","Good because it is frightening"],"Surprisingly or exceptionally good","“Awfully” intensifies “good” here; the two words usually point in opposite directions.");
mc("BOS-OXY-002",O,"Bittersweet","What feeling does “bittersweet” usually describe?",["Only anger","Happiness mixed with sadness","A tasteless experience","Fear without hope"],"Happiness mixed with sadness","It combines pleasure with pain, like a fond memory of a difficult goodbye.");
mc("BOS-OXY-003",O,"Deafening silence","What does “deafening silence” emphasize?",["A loud argument","An unusually noticeable or tense absence of sound","A musical performance","A person who cannot hear"],"An unusually noticeable or tense absence of sound","The contrast makes the silence feel powerful and uncomfortable.");
mc("BOS-OXY-004",O,"Living dead","What does “living dead” suggest in figurative use?",["A lively celebration","A person who seems lifeless or emotionally numb","A ghost story only","A healthy newborn"],"A person who seems lifeless or emotionally numb","The phrase joins being alive with seeming dead.");
mc("BOS-OXY-005",O,"Open secret","What is an “open secret”?",["A secret known by many people","A locked diary","A fact no one knows","A false rumor"],"A secret known by many people","It is supposedly private but widely known.");
mc("BOS-OXY-006",O,"Pretty ugly","What does “pretty ugly” mean in casual speech?",["Beautifully decorated","Quite unattractive","A little beautiful","Impossible to describe"],"Quite unattractive","“Pretty” works as an intensifier, creating a playful contradiction.");
mc("BOS-OXY-007",O,"Original copy","Which meaning best fits “original copy”?",["A reproduction presented as the first or authoritative version","A brand-new invention","A fake with no source","A handwritten letter only"],"A reproduction presented as the first or authoritative version","The words contrast something copied with something original.");
mc("BOS-OXY-008",O,"Only choice","Why can “only choice” work as an oxymoronic expression?",["It says there are many choices","It pairs the idea of choosing with having no alternative","It means a random choice","It describes a perfect choice"],"It pairs the idea of choosing with having no alternative","It stresses that the apparent choice is actually unavoidable.");
mc("BOS-OXY-009",O,"Seriously funny","What does “seriously funny” most likely mean?",["Not funny at all","Extremely funny","Funny only to serious people","A serious warning"],"Extremely funny","“Seriously” is an intensifier despite its contrast with “funny.”");
mc("BOS-OXY-010",O,"The story's title","In Gonzalez's story, how does ordinary pan de sal connect to the narrator's experience?",["It is a treasure he finds at the party","It frames his everyday errand and contrasts ordinary life with youthful longing","It proves he becomes a baker","It is a gift from Aida"],"It frames his everyday errand and contrasts ordinary life with youthful longing","The familiar bread anchors the narrator's daily world as his romantic hopes meet reality.");

// PART III: 20 short-story identifications, exactly four per story.
const S=CATS.stories;
mc("STORY-001",S,"The Necklace","Who is the central character who longs for a life of wealth and high society?",["Jeanne Forestier","Mathilde Loisel","Lumnay","Aida"],"Mathilde Loisel","Mathilde's dissatisfaction with her modest life drives the plot.");
mc("STORY-002",S,"The Necklace","Who lends Mathilde the necklace for the ministry ball?",["Mme Forestier","Mme Loisel","Awiyao","The old mother"],"Mme Forestier","Mathilde borrows the necklace from her wealthy friend Jeanne Forestier.");
mc("STORY-003",S,"The Necklace","What object does Mathilde lose after the ball?",["A pearl comb","A diamond necklace","A silk shawl","A gold watch"],"A diamond necklace","The lost necklace leads the Loisels into years of debt.");
mc("STORY-004",S,"The Necklace","What is the final revelation about the necklace Mathilde replaced?",["It belonged to the minister","It was imitation jewelry and not valuable","It was never lost","It was made by Mathilde"],"It was imitation jewelry and not valuable","The ending makes the couple's years of sacrifice tragically unnecessary.");
mc("STORY-005",S,"Appointment of Love","Who is the author of “Appointment of Love”?",["Guy de Maupassant","Sulamith Ish-Kishor","Matsuo Basho","Amador Daguio"],"Sulamith Ish-Kishor","Ish-Kishor wrote this short story about love and trust.");
mc("STORY-006",S,"Appointment of Love","What does the husband arrange to test in the story?",["His wife's loyalty and love","His brother's courage","The value of a family farm","A stranger's honesty"],"His wife's loyalty and love","The meeting is a test that creates the story's central conflict.");
mc("STORY-007",S,"Appointment of Love","What is central to the conflict between the couple?",["A disagreement about a necklace","A test of trust and the fear of betrayal","A dispute over a throne","A journey delayed by a storm"],"A test of trust and the fear of betrayal","The story turns on whether love can endure suspicion and a staged temptation.");
mc("STORY-008",S,"Appointment of Love","Which theme best fits the story?",["Trust is essential in a loving relationship","War brings glory","Wealth guarantees happiness","Revenge restores justice"],"Trust is essential in a loving relationship","The test exposes how fragile trust can become when love is treated as a trial.");
mc("STORY-009",S,"The Aged Mother","Who wrote “The Aged Mother”?",["Matsuo Basho","N.V.M. Gonzalez","Sulamith Ish-Kishor","Sophocles"],"Matsuo Basho","Basho is credited with the story, also translated as “The Story of the Aged Mother.”");
mc("STORY-010",S,"The Aged Mother","Who carries his elderly mother up the mountain under the ruler's order?",["The young lord","Her son","The village elder","A traveling monk"],"Her son","He loves his mother but faces an order to abandon or kill the elderly.");
mc("STORY-011",S,"The Aged Mother","What does the mother do on the dangerous journey that reveals her care?",["Leaves a trail of broken twigs to guide her son's return","Hides the village's food","Challenges the ruler","Runs ahead to the palace"],"Leaves a trail of broken twigs to guide her son's return","Even while facing death, she thinks of keeping her son safe.");
mc("STORY-012",S,"The Aged Mother","What changes the ruler's view of older people?",["The mother's clever answers to impossible tasks","A battle won by her son","A harvest festival","A message from a neighboring king"],"The mother's clever answers to impossible tasks","Her wisdom convinces the ruler that elders are valuable to society.");
mc("STORY-013",S,"The Bread of Salt","Who narrates “The Bread of Salt”?",["Aida","An unnamed adolescent boy","The town baker","The boy's father"],"An unnamed adolescent boy","The story is told in first person by the young admirer of Aida.");
mc("STORY-014",S,"The Bread of Salt","Who is Aida to the narrator?",["His sister","A young woman he admires","His violin teacher","The baker's daughter"],"A young woman he admires","His idealized crush shapes his hopes and embarrassment.");
mc("STORY-015",S,"The Bread of Salt","What does the narrator bring to the party that contributes to his embarrassment?",["A violin","A cake","A bouquet of roses","A lost necklace"],"A violin","He plays with the orchestra, then feels exposed when his private fantasy meets reality.");
mc("STORY-016",S,"The Bread of Salt","What does pan de sal chiefly suggest in the story?",["The narrator's everyday family life and social world","A royal inheritance","A magic object","A battlefield victory"],"The narrator's everyday family life and social world","The daily bread errand grounds the story in ordinary life and class difference.");
mc("STORY-017",S,"Wedding Dance","Who wrote “The Wedding Dance”?",["Amador Daguio","Guy de Maupassant","Matsuo Basho","N.V.M. Gonzalez"],"Amador Daguio","Daguio's story portrays a painful separation shaped by custom.");
mc("STORY-018",S,"Wedding Dance","Who are the couple at the center of “The Wedding Dance”?",["Mathilde and Loisel","Awiyao and Lumnay","Odysseus and Penelope","Aida and the narrator"],"Awiyao and Lumnay","They part because they have no child and the community expects Awiyao to have an heir.");
mc("STORY-019",S,"Wedding Dance","What conflict forces Awiyao and Lumnay apart?",["They disagree about a lost necklace","Social pressure for an heir conflicts with their love","A storm traps them at sea","A king orders them to leave"],"Social pressure for an heir conflicts with their love","Tradition and the need for children strain their marriage.");
mc("STORY-020",S,"Wedding Dance","What does the wedding gong and dance emphasize?",["The community ritual surrounding marriage and separation","A private city ball","A naval battle","A harvest competition"],"The community ritual surrounding marriage and separation","The public celebration contrasts with the couple's private grief.");

// PART IV: 15 history identifications.
const H=CATS.history;
mc("GREEK-HIST-001",H,"Archaic period","Which broad period is associated with the formation of the Greek polis and the flourishing of Homeric epic and lyric poetry?",["Archaic period","Hellenistic period","Roman Imperial period","Byzantine period"],"Archaic period","The Archaic age (roughly eighth to sixth centuries BCE) saw major developments in epic, lyric, and the polis.");
mc("GREEK-HIST-002",H,"Classical period","Which period is especially associated with fifth-century Athenian tragedy and comedy?",["Classical period","Geometric period","Hellenistic period","Mycenaean period"],"Classical period","Fifth-century BCE Athens became a major center of dramatic performance.");
mc("GREEK-HIST-003",H,"Hellenistic period","What event traditionally marks the beginning of the Hellenistic period?",["The fall of Troy","The death of Alexander the Great","The first Olympic Games","The founding of Rome"],"The death of Alexander the Great","His death in 323 BCE marks the beginning of the Hellenistic age.");
mc("GREEK-HIST-004",H,"Epic poetry","Which feature is most typical of ancient Greek epic poetry?",["Long narrative verse about heroic deeds","Short comic dialogue only","A speech delivered in court","A lyric poem for one singer"],"Long narrative verse about heroic deeds","Epic poetry narrates large-scale heroic stories, often using a repeated oral style.");
mc("GREEK-HIST-005",H,"Homer","Which two major Greek epics are traditionally attributed to Homer?",["The Iliad and The Odyssey","The Theogony and Works and Days","Antigone and Oedipus at Colonus","The Histories and Anabasis"],"The Iliad and The Odyssey","They are the foundational Greek epics about the Trojan War and Odysseus's return.");
mc("GREEK-HIST-006",H,"Lyric poetry","What does the term lyric poetry originally connect to?",["Poems performed with the lyre","Stories carved on stone","Plays performed in masks","Speeches before an assembly"],"Poems performed with the lyre","Lyric poetry often expresses personal or communal feeling and was linked to musical performance.");
mc("GREEK-HIST-007",H,"Sappho","Which poet is especially known for lyric poems expressing personal feeling and desire?",["Sappho","Aristophanes","Herodotus","Aeschylus"],"Sappho","Sappho of Lesbos is one of ancient Greece's most celebrated lyric poets.");
mc("GREEK-HIST-008",H,"Drama","Where did Athenian tragedy and comedy develop as public performance traditions?",["At festivals honoring Dionysus","At Olympic chariot races","In private law courts","At the Pythian battlefield"],"At festivals honoring Dionysus","Drama was performed at civic-religious festivals, especially the City Dionysia.");
mc("GREEK-HIST-009",H,"Tragedy","Which playwright is often credited with adding a second actor and expanding dramatic dialogue?",["Aeschylus","Homer","Sappho","Menander"],"Aeschylus","Ancient tradition credits Aeschylus with important innovations in tragic staging.");
mc("GREEK-HIST-010",H,"Sophocles","Which tragedian wrote Oedipus the King and Antigone?",["Sophocles","Euripides","Aristophanes","Hesiod"],"Sophocles","Sophocles is one of the three major surviving Athenian tragedians.");
mc("GREEK-HIST-011",H,"Euripides","Which tragedian wrote Medea and The Bacchae?",["Euripides","Sophocles","Aeschylus","Pindar"],"Euripides","Euripides is known for intense characters and works such as Medea.");
mc("GREEK-HIST-012",H,"Comedy","Which playwright is a leading representative of Old Comedy?",["Aristophanes","Sophocles","Homer","Herodotus"],"Aristophanes","His plays use satire, fantasy, and political humor.");
mc("GREEK-HIST-013",H,"History","Who is often called the “Father of History” and wrote about the Greco-Persian Wars?",["Herodotus","Thucydides","Hesiod","Pindar"],"Herodotus","Herodotus's Histories investigate the Persian Wars and the cultures involved.");
mc("GREEK-HIST-014",H,"Thucydides","Which historian wrote an account of the Peloponnesian War emphasizing evidence and political analysis?",["Thucydides","Herodotus","Plato","Aeschylus"],"Thucydides","His History of the Peloponnesian War is a foundational work of analytical history.");
mc("GREEK-HIST-015",H,"Hesiod","Which poet composed The Theogony, a genealogy of the gods?",["Hesiod","Homer","Sappho","Sophocles"],"Hesiod","The Theogony describes the origins and family relationships of the gods.");

// PART V: 10 matching-format items (match each name to domain, symbol, family, or myth).
const G=CATS.gods;
mc("GODS-001",G,"Domain","Match Zeus with his principal domain.",["Sea and earthquakes","Sky, thunder, and kingship","Wisdom and crafts","Underworld and wealth"],"Sky, thunder, and kingship","Zeus rules the gods and is associated with the sky and thunder.");
mc("GODS-002",G,"Domain","Match Athena with her principal domain.",["Wisdom and strategic warfare","Love and beauty","Wine and theater","Hearth and home"],"Wisdom and strategic warfare","Athena is the goddess of wisdom and strategic skill.");
mc("GODS-003",G,"Domain","Match Poseidon with his principal domain.",["Sun and music","Sea and earthquakes","Messenger and travel","Marriage and childbirth"],"Sea and earthquakes","Poseidon rules the sea and is associated with earthquakes and horses.");
mc("GODS-004",G,"Domain","Match Aphrodite with her principal domain.",["War and metalwork","Love and beauty","Hunt and wilderness","Harvest and grain"],"Love and beauty","Aphrodite is the goddess associated with love and beauty.");
mc("GODS-005",G,"Symbols","Which symbol is most closely associated with Apollo?",["Lyre","Trident","Owl","Thunderbolt"],"Lyre","Apollo is associated with music, prophecy, healing, and the lyre.");
mc("GODS-006",G,"Symbol","Which animal is a familiar symbol of Athena?",["Owl","Dolphin","Peacock","Boar"],"Owl","The owl represents Athena's wisdom.");
mc("GODS-007",G,"Family","Who is Zeus's wife and queen of the Olympian gods?",["Hera","Aphrodite","Demeter","Athena"],"Hera","Hera is Zeus's wife and queen of the gods.");
mc("GODS-008",G,"Family","Who is Hermes's father in Greek mythology?",["Zeus","Poseidon","Hades","Hephaestus"],"Zeus","Hermes is the son of Zeus and the nymph Maia.");
mc("GODS-009",G,"Myth","Which goddess helps Odysseus and Telemachus throughout The Odyssey?",["Athena","Hera","Demeter","Aphrodite"],"Athena","Athena intervenes repeatedly to aid Odysseus and his son.");
mc("GODS-010",G,"Myth","Which god's anger makes Odysseus's sea voyage home especially difficult?",["Apollo","Poseidon","Ares","Dionysus"],"Poseidon","Poseidon punishes Odysseus after the blinding of Polyphemus.");

// PART VI: ten application and analysis questions.
const Q=CATS.qualities;
mc("QUAL-001",Q,"Heroism","A hero risks personal safety to protect companions. Which Greek-literature quality is most clearly shown?",["Heroism","Comic relief","Mere luck","Pastoral simplicity"],"Heroism","Greek heroes are often tested through courage, endurance, and responsibility.");
mc("QUAL-002",Q,"Fate","A prophecy is fulfilled even as characters try to escape it. Which concept does this illustrate?",["Fate","Hospitality","Lyric voice","Satire"],"Fate","Greek stories often show fate as a powerful limit on human control.");
mc("QUAL-003",Q,"Divine intervention","A goddess disguises a hero and guides him through danger. What literary feature is at work?",["Divine intervention","Realism","Parody","Anagnorisis only"],"Divine intervention","A deity directly affects human events and helps shape the plot.");
mc("QUAL-004",Q,"Honor and glory","A warrior chooses a dangerous battle because lasting honor matters more to him than a quiet life. Which value motivates him?",["Honor and glory","Domestic comfort","Anonymity","Comic misunderstanding"],"Honor and glory","Kleos, or lasting fame, is a major heroic value in epic poetry.");
mc("QUAL-005",Q,"Tragic flaw","A powerful ruler's confidence becomes stubborn refusal to listen, helping bring about his downfall. What does this show?",["A tragic flaw","A deus ex machina","A pastoral convention","A comic subplot"],"A tragic flaw","A character's damaging trait contributes to suffering or reversal.");
mc("QUAL-006",Q,"Human and divine","A character receives divine help but still must make a difficult choice. What idea does this balance suggest?",["Human choices matter alongside divine forces","Gods erase all human responsibility","Fate never affects people","The story has no conflict"],"Human choices matter alongside divine forces","Greek literature often combines divine influence with human agency and responsibility.");
mc("QUAL-007",Q,"Mythology","Why do Greek literary works use familiar myths and gods?",["Shared myths give audiences a framework for exploring human choices","Myths remove every need for characterization","Gods appear only as decoration","Myths prevent stories from having themes"],"Shared myths give audiences a framework for exploring human choices","Myth supplies recognizable stories through which writers examine identity, duty, and power.");
mc("QUAL-008",Q,"Moral lesson","A tale shows pride causing a person to ignore warnings and suffer. What lesson is emphasized?",["Unchecked pride can lead to harm","Wealth always brings wisdom","Warnings should never be trusted","Fate can be defeated by force"],"Unchecked pride can lead to harm","Greek narratives often warn that excessive pride can distort judgment.");
mc("QUAL-009",Q,"Loyalty","A spouse remains faithful through a long absence and resists pressure to remarry. Which theme is central?",["Loyalty","Conquest","Revenge","Ambition"],"Loyalty","Faithfulness to family and home is central to The Odyssey.");
add("QUAL-010",Q,"Symbolism","Short answer: In an epic, a homecoming journey represents restoring family and identity as well as reaching a place. What literary device is this?",null,"Symbolism","The journey carries meaning beyond its literal travel: it represents belonging and restored order.","Normal","Short Answer");

// PART VII: 20 multiple-choice work questions: 7 Iliad, 7 Odyssey, 6 Oedipus.
const W=CATS.works;
mc("LIT-MCQ-001",W,"The Iliad","What is the central conflict that begins The Iliad?",["Achilles' anger after a quarrel with Agamemnon","Odysseus's dispute with Poseidon","Oedipus's search for his parents","Hector's journey to Ithaca"],"Achilles' anger after a quarrel with Agamemnon","The poem opens with the anger of Achilles after Agamemnon takes Briseis.");
mc("LIT-MCQ-002",W,"The Iliad","Who is the Trojan prince and champion killed by Achilles?",["Paris","Hector","Aeneas","Priam"],"Hector","Hector is Troy's leading defender and the son of King Priam.");
mc("LIT-MCQ-003",W,"The Iliad","Why does Achilles return to battle after Patroclus dies?",["He seeks revenge on Hector","Athena orders him to sail home","He wants to win a chariot race","Agamemnon returns Briseis"],"He seeks revenge on Hector","Patroclus's death changes Achilles's priorities and drives him back into combat.");
mc("LIT-MCQ-004",W,"The Iliad","Who is Patroclus to Achilles?",["His close companion","His father","His enemy king","His son"],"His close companion","Patroclus is Achilles's beloved companion and fellow Greek warrior.");
mc("LIT-MCQ-005",W,"The Iliad","Which goddess supports the Greek side and helps Achilles early in the poem?",["Athena","Aphrodite","Demeter","Hestia"],"Athena","Athena restrains Achilles from killing Agamemnon and favors the Greeks.");
mc("LIT-MCQ-006",W,"The Iliad","What does King Priam ask Achilles to return to him?",["Hector's body","The Trojan Horse","A golden shield","Helen's necklace"],"Hector's body","Priam's appeal as a grieving father leads Achilles to show compassion.");
mc("LIT-MCQ-007",W,"The Iliad","Which theme is strongly explored through Achilles's anger and grief?",["Honor, mortality, and the cost of war","The joy of farming","The invention of comedy","The founding of Athens"],"Honor, mortality, and the cost of war","The epic examines heroic glory alongside grief and the suffering caused by war.");
mc("LIT-MCQ-008",W,"The Odyssey","What is Odysseus trying to do throughout The Odyssey?",["Return to Ithaca after the Trojan War","Conquer Troy","Become king of Sparta","Find the Golden Fleece"],"Return to Ithaca after the Trojan War","The poem follows his long nostos, or homecoming journey.");
mc("LIT-MCQ-009",W,"The Odyssey","What name does Odysseus use to trick Polyphemus?",["Nobody","Ithacan","Nestor","No-man's Son"],"Nobody","When Polyphemus cries that “Nobody” is hurting him, the other Cyclopes do not help.");
mc("LIT-MCQ-010",W,"The Odyssey","How does Odysseus and his crew escape the blinded Cyclops?",["They cling beneath the sheep","They swim through a secret tunnel","Athena opens the cave","They ride away on winged horses"],"They cling beneath the sheep","Polyphemus feels the animals' backs but does not detect the men underneath.");
mc("LIT-MCQ-011",W,"The Odyssey","Why does Odysseus conceal his identity when he first returns to Ithaca?",["To assess the household and plan against the suitors","He has forgotten his name","Athena forbids him to speak","He wants to join the suitors"],"To assess the household and plan against the suitors","Disguise lets him learn who is loyal before he reveals himself.");
mc("LIT-MCQ-012",W,"The Odyssey","What challenge allows Penelope to help identify Odysseus?",["Stringing Odysseus's bow","Crossing the sea on a raft","Naming every Olympian","Winning a footrace"],"Stringing Odysseus's bow","Only Odysseus can string the bow and complete the test.");
mc("LIT-MCQ-013",W,"The Odyssey","What does the olive-tree bed reveal about Odysseus and Penelope?",["Their shared knowledge and the permanence of their marriage","That Penelope has never seen Ithaca","That the suitors built the palace","That Odysseus is a god"],"Their shared knowledge and the permanence of their marriage","The bed's construction is a private secret that confirms Odysseus's identity.");
mc("LIT-MCQ-014",W,"The Odyssey","Which quality best describes Penelope's response to the suitors?",["Clever patience and loyalty","Reckless pride","Indifference to Ithaca","Desire for war"],"Clever patience and loyalty","She delays remarriage with intelligence while remaining loyal to Odysseus.");
mc("LIT-MCQ-015",W,"Oedipus the King","Who wrote Oedipus the King?",["Sophocles","Homer","Aristophanes","Euripides"],"Sophocles","Sophocles wrote this Athenian tragedy about Oedipus and Thebes.");
mc("LIT-MCQ-016",W,"Oedipus the King","What problem does Oedipus try to solve at the beginning of the play?",["A plague afflicting Thebes","A Greek fleet lost at sea","A famine in Ithaca","A war between Athens and Sparta"],"A plague afflicting Thebes","Oedipus investigates the murder of Laius to end the plague.");
mc("LIT-MCQ-017",W,"Oedipus the King","What does the oracle say must happen for Thebes to be free of the plague?",["Laius's killer must be found and punished or driven out","The city must build a ship","Oedipus must marry Antigone","The people must abandon all temples"],"Laius's killer must be found and punished or driven out","The search for Laius's murderer drives the investigation and reversal.");
mc("LIT-MCQ-018",W,"Oedipus the King","What is the key truth Oedipus discovers about himself?",["He killed his father Laius and married his mother Jocasta","He is the son of Creon","He caused the Trojan War","He is actually Tiresias"],"He killed his father Laius and married his mother Jocasta","The prophecy has been fulfilled despite efforts to avoid it.");
mc("LIT-MCQ-019",W,"Oedipus the King","What does Oedipus's search for truth show about his character?",["His determination can become relentless even when the truth threatens him","He refuses to investigate anything","He is guided only by greed","He wants to abandon Thebes"],"His determination can become relentless even when the truth threatens him","His persistence is admirable but also drives him toward devastating knowledge.");
mc("LIT-MCQ-020",W,"Oedipus the King","Which contrast is central to the play's imagery and ideas?",["Physical sight and inner understanding","Winter and summer farming","Sea travel and horse racing","Comedy and lyric song"],"Physical sight and inner understanding","The blind prophet sees the truth while sighted Oedipus cannot recognize it.");

// Free-response sections use typed recall; only the works section remains multiple choice.
qbank.forEach(q=>{if(q.category===CATS.stories||q.category===CATS.history){q.kind="Identification";q.choices=null}else if(q.category===CATS.lines||q.category===CATS.oxymorons||q.category===CATS.qualities){q.kind="Written Answer";q.choices=null}});
const EXPECTED={lines:15,oxymorons:10,stories:20,history:15,gods:10,qualities:10,works:20};
const TOPIC_TO_CAT=Object.fromEntries(Object.entries(CATS).map(([k,v])=>[v,k]));
const STORAGE_KEY="greeklit-study-hub-v1";
const freshState=()=>({answered:{},mistakes:[],scores:[],flashcards:{},settings:{difficulty:"Any"},streak:0,lastStudy:null});
function loadState(){try{return {...freshState(),...JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")}}catch{return freshState()}}
let state=loadState();
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updateMistakeBadge()}
function updateMistakeBadge(){const el=document.getElementById("mistake-count");if(el)el.textContent=state.mistakes.length}
function applyTheme(){const dark=state.settings?.theme==="dark";document.documentElement.dataset.theme=dark?"dark":"light";const toggle=document.querySelector(".theme-toggle");if(toggle){toggle.textContent=dark?"☀":"☾";toggle.title=dark?"Switch to light mode":"Switch to dark mode";toggle.setAttribute("aria-label",toggle.title)}const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=dark?"#1b1d1e":"#f6f3ec"}
function toggleTheme(){state.settings??={};state.settings.theme=state.settings.theme==="dark"?"light":"dark";saveState();applyTheme();if(activePage==="settings")renderSettings()}
function shuffled(items){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function pct(a,b){return b?Math.round(a/b*100):0}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function categoryFor(q){return TOPIC_TO_CAT[q.category]||"works"}
function performance(){const map={};for(const key of Object.keys(CATS)){const qs=qbank.filter(q=>categoryFor(q)===key),done=qs.filter(q=>state.answered[q.id]),right=done.filter(q=>state.answered[q.id]===true).length;map[key]={total:qs.length,done:done.length,right,accuracy:pct(right,done.length),remaining:qs.length-done.length}}return map}
function weakestTopic(){const p=performance();return Object.entries(p).filter(([,v])=>v.done).sort((a,b)=>a[1].accuracy-b[1].accuracy)[0]}
function topicsProgress(){return Object.entries(CATS).map(([key,title])=>{const p=performance()[key];return `<div class="topic-card" data-topic="${key}"><div class="topic-top"><div class="topic-icon">${topicIcon(key)}</div><div><div class="topic-name">${title}</div><div class="topic-sub">${p.done} of ${p.total} practiced</div></div><div class="topic-score">${p.done?p.accuracy+"%":"—"}</div></div><div class="progress-track"><div class="progress-fill" style="width:${p.total?p.done/p.total*100:0}%"></div></div><div class="topic-foot"><span>${p.done?`${p.right} correct`:"Not started"}</span><span>${p.remaining} remaining</span></div></div>`}).join("")}
function topicIcon(k){return ({lines:"❞",oxymorons:"◈",stories:"▤",history:"⌘",gods:"♙",qualities:"✦",works:"⚔"})[k]||"✦"}
function totalStats(){let done=Object.keys(state.answered).length,right=Object.values(state.answered).filter(Boolean).length;return {done,right,wrong:done-right,accuracy:pct(right,done)}}
const pageContent=document.getElementById("page-content");let activePage="dashboard",quiz=null,flash={items:[],index:0,revealed:false};
function setPage(page){activePage=page;document.querySelectorAll("[data-page]").forEach(el=>el.classList.toggle("active",el.dataset.page===page));document.getElementById("page-name").textContent=({dashboard:"Dashboard",topics:"Study Topics",practice:"Practice Quiz",rapid:"Rapid Fire",flashcards:"Quick Review",exam:"Exam Mode",mistakes:"Review My Mistakes",progress:"Study Progress",settings:"Settings"})[page]||"Dashboard";document.getElementById("sidebar").classList.remove("open");renderPage()}
function renderPage(){if(quiz){renderQuiz();return}const view={dashboard:renderDashboard,topics:renderTopics,practice:()=>renderSetup("practice"),rapid:()=>renderSetup("rapid"),exam:()=>renderSetup("exam"),mistakes:renderMistakes,progress:renderProgress,flashcards:renderFlashcards,settings:renderSettings};(view[activePage]||renderDashboard)()}
function renderDashboard(){const s=totalStats(),weak=weakestTopic(),recommend=weak?`<div class="recommend"><span class="recommend-icon">◎</span><div><b>${CATS[weak[0]]} could use a little practice</b><p>Your accuracy here is ${weak[1].accuracy}%. A short focused set can help strengthen recall.</p><button class="text-link" data-action="practice-topic" data-topic="${weak[0]}">Practice this topic →</button></div></div>`:`<div class="recommend"><span class="recommend-icon">✦</span><div><b>Your review plan starts here</b><p>Try a short practice set. We’ll recommend a topic based on the questions you find tricky.</p><button class="text-link" data-page="practice">Start a practice set →</button></div></div>`;const recent=state.scores.slice(-3).reverse();pageContent.innerHTML=`<div class="welcome-row"><div><div class="eyebrow">A LITTLE PRACTICE GOES A LONG WAY</div><h1 class="page-title">Good ${greeting()}, ready to learn?</h1><p class="subtitle">Build confidence for your Literature exam, one question at a time.</p><div class="pattern"></div></div><button class="primary-btn" data-page="practice">Start practicing <span class="btn-arrow">→</span></button></div><div class="stats-grid"><div class="stat-card"><div class="stat-top">Questions answered <span class="stat-icon">◉</span></div><div class="stat-value">${s.done}</div><div class="stat-foot">of 100 in the question bank</div></div><div class="stat-card"><div class="stat-top">Correct answers <span class="stat-icon">✓</span></div><div class="stat-value">${s.right}</div><div class="stat-foot">Keep your recall sharp</div></div><div class="stat-card"><div class="stat-top">Overall accuracy <span class="stat-icon">↗</span></div><div class="stat-value">${s.accuracy}%</div><div class="stat-foot">Across questions you've answered</div></div><div class="stat-card"><div class="stat-top">Saved mistakes <span class="stat-icon">↻</span></div><div class="stat-value">${state.mistakes.length}</div><div class="stat-foot">Ready for another review</div></div></div><div class="section-head"><h2>Your study topics</h2><button class="text-link" data-page="topics">View all topics →</button></div><div class="topic-grid">${topicsProgress()}</div><div class="dashboard-lower"><section class="panel"><h3>What should I study?</h3>${recommend}</section><section class="panel"><h3>Recent practice</h3>${recent.length?recent.map(r=>`<div class="recent-row"><span>${esc(r.label)} · ${new Date(r.date).toLocaleDateString()}</span><span class="score-pill">${r.score}/${r.total}</span></div>`).join(""):`<div class="recent-empty">Your quiz scores will show here after your first practice.</div>`}</section></div>`}
function greeting(){const h=new Date().getHours();return h<12?"morning":h<18?"afternoon":"evening"}
function renderTopics(){pageContent.innerHTML=`<div class="eyebrow">YOUR EXAM, ORGANIZED</div><h1 class="page-title">Study topics</h1><p class="subtitle">Choose a section to practice its questions or browse a quick reference.</p><div class="section-head"><h2>All 7 exam sections <span class="small">· exactly 100 questions</span></h2></div><div class="topic-grid">${topicsProgress()}</div><div class="section-head"><h2>Greek gods quick reference</h2><span class="small">Domains and familiar symbols</span></div><div class="god-grid">${godReference()}</div>`}
function godReference(){return [["Zeus","Sky, thunder, kingship · thunderbolt","Brother of Poseidon and Hades."],["Hera","Marriage and queenship · peacock","Wife and sister of Zeus."],["Poseidon","Sea, earthquakes · trident","Brother of Zeus; father of Polyphemus in the Odyssey."],["Athena","Wisdom, strategy · owl","Daughter of Zeus; helper of Odysseus."],["Apollo","Music, prophecy · lyre","Son of Zeus; twin of Artemis."],["Artemis","Hunt and wilderness · bow","Daughter of Zeus; twin of Apollo."],["Aphrodite","Love and beauty · dove","Goddess associated with desire and attraction."],["Hermes","Messages and travel · winged sandals","Son of Zeus and Maia; messenger of the gods."],["Ares","War · spear","Son of Zeus and Hera in common traditions."],["Demeter","Harvest and grain · sheaf","Mother of Persephone."],["Hephaestus","Fire and metalwork · hammer","Divine smith, commonly said to be Hera's son."],["Dionysus","Wine and theater · ivy","God honored at festivals where drama developed."]].map(x=>`<div class="god-card"><b>${x[0]}</b><p>${x[1]}<br>${x[2]}</p></div>`).join("")}
function renderSetup(mode){const title=mode==="exam"?"Exam Mode":mode==="rapid"?"Rapid Fire":"Practice quiz",intro=mode==="exam"?"Take the full 100-question exam in randomized order, with all seven sections represented.":mode==="rapid"?"Fast, focused recall: answer each question and move straight on.":"Choose a format and build a focused practice set from the fixed 100-question bank.";pageContent.innerHTML=`<div class="eyebrow">ACTIVE RECALL</div><h1 class="page-title">${title}</h1><p class="subtitle">${intro}</p>${mode==="exam"?`<div class="toolbar"><span class="small">7 parts · 100 unique questions · randomized order</span><span class="small">Timer begins when you start</span></div>`:""}<div class="two-col" style="margin-top:22px"><section class="setup-card"><h3>Make it your session</h3><p>Questions are selected from the master bank. No new questions are generated.</p><label class="field-label" for="quiz-type">Quiz type</label><select id="quiz-type"><option value="all">${mode==="rapid"?"Rapid Fire · Mixed":"Mixed Quiz · All question types"}</option>${[["lines","Characters' Lines"],["oxymorons","Oxymoronic Expressions"],["identification","Identification"],["matching","Matching Type"],["analysis","Analysis"],["multiple","Multiple Choice"]].map(([v,l])=>`<option value="${v}">${l}</option>`).join("")}</select><label class="field-label" for="quiz-topic">Topic</label><select id="quiz-topic"><option value="all">All topics</option>${Object.entries(CATS).map(([k,v])=>`<option value="${k}">${v}</option>`).join("")}</select><label class="field-label" for="quiz-difficulty">Difficulty</label><select id="quiz-difficulty"><option>Any</option><option>Easy</option><option>Normal</option><option>Hard</option></select><label class="field-label">Number of questions</label><div class="choice-chips" id="count-chips">${(mode==="exam"?[100]:[5,10,20,50,100]).map((n,i)=>`<button class="chip ${i===0?"selected":""}" data-count="${n}">${n}</button>`).join("")}</div><div class="setup-actions"><button class="primary-btn" data-action="start-quiz" data-mode="${mode}">${mode==="exam"?"Begin exam":mode==="rapid"?"Start rapid fire":"Start quiz"} <span class="btn-arrow">→</span></button></div></section><section class="setup-card"><h3>Session guide</h3><p>One question at a time. After each answer, see the correct response and a short reason to help it stick.</p><div class="setting-row"><span>Question bank</span><b>100 fixed questions</b></div><div class="setting-row"><span>Questions already answered</span><b>${totalStats().done} / 100</b></div><div class="setting-row"><span>Saved for mistake review</span><b>${state.mistakes.length}</b></div><div class="setting-row"><span>Recent sessions</span><b>${state.scores.length}</b></div><p style="margin-top:18px">For a custom set, select one section or combine sections, then choose a question count.</p></section></div>`}
function getSelectedCount(){return Number(document.querySelector(".chip.selected")?.dataset.count||5)}
function startQuiz(mode,onlyMistakes=false,topicOverride=null){
 const topic=topicOverride||document.getElementById("quiz-topic")?.value||"all",type=document.getElementById("quiz-type")?.value||"all",difficulty=document.getElementById("quiz-difficulty")?.value||"Any";
 let pool=onlyMistakes?qbank.filter(q=>state.mistakes.some(m=>m.id===q.id)):qbank.filter(q=>(topic==="all"||categoryFor(q)===topic)&&(difficulty==="Any"||q.difficulty===difficulty)&&typeMatches(q,type));
 if(!pool.length){toast("No saved questions fit those choices yet.");return}
 const count=mode==="exam"?100:onlyMistakes?pool.length:Math.min(getSelectedCount(),pool.length),matching=type==="matching"&&!onlyMistakes&&mode!=="exam";
 let matchingRounds=[];
 if(matching){const candidates=shuffled(pool).slice(0,count);for(let i=0;i<candidates.length;i+=5)matchingRounds.push(candidates.slice(i,i+5))}
 const picked=matching?matchingRounds.flat():count===pool.length?pool:shuffled(pool).slice(0,count);
 quiz={items:matching?picked:mode==="exam"?shuffled(qbank):shuffled(picked),matching,matchingRounds,round:0,responseSets:[],index:0,answers:[],selected:null,checked:false,mode,started:Date.now(),onlyMistakes,label:matching?"Matching Type - Greek Gods":onlyMistakes?"Mistake review":mode==="exam"?"Full exam":mode==="rapid"?"Rapid Fire":topic==="all"?"Practice quiz":CATS[topic]};
 renderQuiz()
}
function typeMatches(q,t){if(t==="all")return true;if(t==="lines")return categoryFor(q)==="lines";if(t==="oxymorons")return categoryFor(q)==="oxymorons";if(t==="identification")return ["stories","history"].includes(categoryFor(q));if(t==="matching")return categoryFor(q)==="gods";if(t==="analysis")return categoryFor(q)==="qualities";if(t==="multiple")return categoryFor(q)==="works";return true}
function renderQuiz(){if(!quiz)return;if(quiz.matching){renderMatchingQuiz();return}const q=quiz.items[quiz.index];if(!q){finishQuiz();return}const n=quiz.index+1,total=quiz.items.length,done=quiz.checked,selected=quiz.selected,correct=selected===q.answer,cat=categoryFor(q);const response=q.choices?`<div class="options">${q.choices.map((ch,i)=>{let cls="option";if(done&&ch===q.answer)cls+=" correct";else if(done&&ch===selected)cls+=" wrong";else if(ch===selected)cls+=" selected";return `<button class="${cls}" ${done?"disabled":""} data-action="answer" data-answer="${esc(ch)}"><span class="option-key">${String.fromCharCode(65+i)}</span><span>${esc(ch)}</span></button>`}).join("")}</div>`:`<textarea class="answer-input" id="short-answer" placeholder="${q.kind==="Identification"||q.kind==="Written Answer"?"Type your answer here...":"Write a short answer..."}" ${done?"disabled":""}>${selected?esc(selected):""}</textarea>`;pageContent.innerHTML=`<div class="quiz-wrap"><div class="quiz-meta"><span>${esc(quiz.label)}${quiz.mode==="exam"?` | ${formatTime(Date.now()-quiz.started)}`:""}</span><span>Question ${n} of ${total}</span></div><div class="quiz-progress"><div style="width:${(n-1+(done?1:0))/total*100}%"></div></div><div class="question-card"><span class="q-tag">${esc(q.topic)} | ${esc(q.kind)}</span><div class="question-text">${esc(q.prompt)}</div>${response}${done?`<div class="feedback ${correct?"good":"bad"}"><b>${correct?"Correct!":"Not quite."} ${correct?"":"Correct answer: "+esc(q.answer)}</b>${esc(q.explanation)}</div>`:""}<div class="quiz-controls"><span class="muted-note">${done?`Difficulty: ${q.difficulty}`:"Think it through, then choose an answer."}</span>${done?`<button class="primary-btn" data-action="next-question">${n===total?"See results":"Next question"} </button>`:q.choices?`<span class="small">Select an answer to check it</span>`:`<button class="primary-btn" data-action="check-text">Check answer</button>`}</div></div><button class="text-link" style="margin-top:16px" data-action="exit-quiz">Leave session</button></div>`}
function renderMatchingQuiz(){const round=quiz.matchingRounds[quiz.round];if(!round){finishQuiz();return}const total=quiz.items.length,first=quiz.index+1,last=quiz.index+round.length,done=quiz.checked;quiz.responseSets[quiz.round]??=shuffled(round.map(q=>q.answer));const responses=quiz.responseSets[quiz.round];const rows=round.map((q,i)=>{const result=quiz.answers[quiz.index+i],letter=result?responses.indexOf(result.answer):-1,feedback=done?result.correct?`<div class="match-feedback correct">Correct. ${esc(q.explanation)}</div>`:`<div class="match-feedback wrong">Correct response: ${esc(q.answer)}. ${esc(q.explanation)}</div>`:"";return `<div class="matching-row ${done?(result.correct?"is-correct":"is-wrong"):""}"><div class="matching-premise"><span class="match-number">${String(quiz.index+i+1).padStart(2,"0")}</span><span>${esc(q.prompt)}</span></div><select id="match-${q.id}" aria-label="Choose the matching response for item ${quiz.index+i+1}" ${done?"disabled":""}><option value="">Choose a response</option>${responses.map((answer,j)=>`<option value="${j}" ${letter===j?"selected":""}>${String.fromCharCode(65+j)}. ${esc(answer)}</option>`).join("")}</select>${feedback}</div>`}).join("");pageContent.innerHTML=`<div class="quiz-wrap matching-quiz"><div class="quiz-meta"><span>${esc(quiz.label)}</span><span>Questions ${first}-${last} of ${total}</span></div><div class="quiz-progress"><div style="width:${(done?last:quiz.index)/total*100}%"></div></div><div class="question-card"><span class="q-tag">Greek Gods &amp; Goddesses | Matching Type</span><p class="matching-instructions">Match each premise in Column A with a response in Column B. Choose a letter for every row, then check your matches.</p><div class="matching-columns"><section class="matching-column"><header><span>Column A</span><small>PREMISES</small></header>${rows}</section><section class="matching-column response-column"><header><span>Column B</span><small>RESPONSES</small></header><ol class="matching-responses">${responses.map((answer,i)=>`<li><span>${String.fromCharCode(65+i)}</span><div>${esc(answer)}</div></li>`).join("")}</ol></section></div><div class="quiz-controls"><span class="muted-note">${done?"Review the matches and explanations above.":"Each response is used once."}</span>${done?`<button class="primary-btn" data-action="next-matching">${quiz.index+round.length>=total?"See results":"Next set"} </button>`:`<button class="primary-btn" data-action="check-matching">Check matches</button>`}</div></div><button class="text-link" style="margin-top:16px" data-action="exit-quiz">Leave session</button></div>`}
function checkMatching(){if(!quiz||quiz.checked)return;const round=quiz.matchingRounds[quiz.round],responses=quiz.responseSets[quiz.round];round.forEach((q,i)=>{const choice=document.getElementById(`match-${q.id}`)?.value,answer=choice===""||choice==null?"(No response selected)":responses[Number(choice)],correct=answer===q.answer;quiz.answers[quiz.index+i]={id:q.id,answer,correct};state.answered[q.id]=correct;state.mistakes=state.mistakes.filter(m=>m.id!==q.id);if(!correct)state.mistakes.push({id:q.id,answer,at:Date.now()})});quiz.checked=true;const today=new Date().toISOString().slice(0,10);if(state.lastStudy!==today){state.streak=state.lastStudy&&((new Date(today)-new Date(state.lastStudy))/86400000===1)?(state.streak||0)+1:1;state.lastStudy=today}saveState();document.getElementById("streak-number").textContent=`${state.streak||0} day streak`;renderQuiz()}
function normalize(s){return String(s||"").trim().toLowerCase().replace(/[.,!?;:]/g,"").replace(/\s+/g," ")}
function checkAnswer(answer){if(!quiz||quiz.checked||answer==null||!String(answer).trim())return;const q=quiz.items[quiz.index],correct=normalize(answer)===normalize(q.answer);quiz.selected=answer;quiz.checked=true;quiz.answers[quiz.index]={id:q.id,answer,correct};state.answered[q.id]=correct;state.mistakes=state.mistakes.filter(m=>m.id!==q.id);if(!correct)state.mistakes.push({id:q.id,answer,at:Date.now()});const today=new Date().toISOString().slice(0,10);if(state.lastStudy!==today){state.streak=state.lastStudy&&((new Date(today)-new Date(state.lastStudy))/86400000===1)?(state.streak||0)+1:1;state.lastStudy=today}saveState();document.getElementById("streak-number").textContent=`${state.streak||0} day streak`;renderQuiz()}
function finishQuiz(){const answers=quiz.answers.filter(Boolean),right=answers.filter(a=>a.correct).length,total=answers.length,by={};answers.forEach(a=>{const q=qbank.find(x=>x.id===a.id),k=categoryFor(q);by[k]??={right:0,total:0};by[k].total++;if(a.correct)by[k].right++});const sorted=Object.entries(by).sort((a,b)=>a[1].right/a[1].total-b[1].right/b[1].total),weakest=sorted[0],strongest=sorted[sorted.length-1];const score={score:right,total,correct:right,wrong:total-right,date:new Date().toISOString(),label:quiz.label,by};state.scores.push(score);if(state.scores.length>30)state.scores=state.scores.slice(-30);saveState();quiz=null;pageContent.innerHTML=`<div class="quiz-wrap"><div class="question-card"><div class="result-hero"><div class="result-circle">${pct(right,total)}%</div><h2>${activePage==="exam"?"Exam complete":"Nice work — session complete"}</h2><p>${activePage==="exam"?"Your full-bank exam results are ready.":"Every question is another step toward exam day."}</p><div class="pattern" style="margin:15px auto"></div></div><div class="result-stats"><div class="result-stat"><b>${right}/${total}</b><span>FINAL SCORE</span></div><div class="result-stat"><b>${right}</b><span>CORRECT</span></div><div class="result-stat"><b>${total-right}</b><span>INCORRECT</span></div></div>${activePage==="exam"?`<div class="section-head"><h2>Performance by category</h2></div>`:""}${Object.entries(by).map(([k,v])=>`<div class="breakdown-row"><label>${CATS[k]}</label><span>${v.right}/${v.total} · ${pct(v.right,v.total)}%</span><div class="progress-track"><div class="progress-fill" style="width:${pct(v.right,v.total)}%"></div></div></div>`).join("")}${activePage==="exam"&&weakest?`<div class="setting-row"><span>Weakest category</span><b>${CATS[weakest[0]]}</b></div><div class="setting-row"><span>Strongest category</span><b>${CATS[strongest[0]]}</b></div>`:""}${weakest?`<div class="recommend" style="margin-top:17px"><span class="recommend-icon">◎</span><div><b>Recommended review: ${CATS[weakest[0]]}</b><p>${weakest[1].right} correct out of ${weakest[1].total} in this category. Review the questions you missed and try them again.</p></div></div>`:""}<div class="setup-actions" style="gap:9px"><button class="secondary-btn" data-page="dashboard">Back to dashboard</button><button class="primary-btn" data-page="mistakes">Review mistakes</button></div></div></div>`;document.getElementById("page-name").textContent="Results"}
function formatTime(ms){const n=Math.floor(ms/1000),m=String(Math.floor(n/60)).padStart(2,"0"),s=String(n%60).padStart(2,"0");return `${m}:${s}`}
function renderMistakes(){const rows=state.mistakes.map(m=>{const q=qbank.find(x=>x.id===m.id);if(!q)return"";return `<article class="mistake-row"><button class="secondary-btn mistake-action" data-action="practice-mistakes">Practice</button><h4>${esc(q.prompt)}</h4><div class="mistake-details"><strong>Your answer:</strong> ${esc(m.answer)}<br><strong>Correct answer:</strong> ${esc(q.answer)}<br><strong>Why:</strong> ${esc(q.explanation)}<br><strong>Topic:</strong> ${esc(q.category)} · ${esc(q.topic)} <span class="small">· ${esc(q.id)}</span></div></article>`}).join("");pageContent.innerHTML=`<div class="eyebrow">TURN MISSES INTO MOMENTUM</div><h1 class="page-title">Review my mistakes</h1><p class="subtitle">Questions you missed are saved here. Get them right in a later quiz and they leave your review list.</p><div class="panel" style="margin-top:20px">${state.mistakes.length?`<div class="section-head" style="margin-top:0"><h2>${state.mistakes.length} question${state.mistakes.length===1?"":"s"} to revisit</h2><button class="primary-btn" data-action="practice-mistakes">Practice my mistakes →</button></div>${rows}`:`<div class="empty-state"><div class="empty-icon">✓</div><h3>No mistakes saved</h3><p>When you miss a question, it will appear here with the right answer and a short explanation.</p><button class="primary-btn" data-page="practice">Start practicing</button></div>`}</div>`}
function renderProgress(){const s=totalStats(),rows=Object.entries(CATS).map(([k,title])=>{const p=performance()[k];return `<div class="breakdown-row"><label>${title}</label><span>${p.right}/${p.done} correct · ${p.done}/${p.total} practiced</span><div class="progress-track"><div class="progress-fill" style="width:${p.total?p.done/p.total*100:0}%"></div></div></div>`}).join("");pageContent.innerHTML=`<div class="eyebrow">YOUR LEARNING, AT A GLANCE</div><h1 class="page-title">Study progress</h1><p class="subtitle">Progress is saved on this device and updates as you answer questions.</p><div class="stats-grid" style="margin-top:21px"><div class="stat-card"><div class="stat-top">Total answered <span class="stat-icon">◉</span></div><div class="stat-value">${s.done}</div><div class="stat-foot">Unique questions practiced</div></div><div class="stat-card"><div class="stat-top">Correct <span class="stat-icon">✓</span></div><div class="stat-value">${s.right}</div><div class="stat-foot">Questions answered correctly</div></div><div class="stat-card"><div class="stat-top">Incorrect <span class="stat-icon">↻</span></div><div class="stat-value">${s.wrong}</div><div class="stat-foot">Revisit any time in mistakes</div></div><div class="stat-card"><div class="stat-top">Accuracy <span class="stat-icon">↗</span></div><div class="stat-value">${s.accuracy}%</div><div class="stat-foot">Across unique questions attempted</div></div></div><section class="panel"><h3>Progress by topic</h3>${rows}</section><section class="panel" style="margin-top:15px"><h3>Recent quiz scores</h3>${state.scores.length?state.scores.slice(-8).reverse().map(r=>`<div class="recent-row"><span>${esc(r.label)} · ${new Date(r.date).toLocaleString()}</span><span class="score-pill">${r.score}/${r.total} · ${pct(r.score,r.total)}%</span></div>`).join(""):`<div class="recent-empty">Finish a quiz to see your scores here.</div>`}</section>`}
function renderFlashcards(){const pool=flash.items.length?flash.items:qbank;const card=pool[flash.index%pool.length];if(!card){pageContent.innerHTML=`<div class="empty-state">No cards available.</div>`;return}const front=card.prompt,back=`${card.answer} — ${card.explanation}`;pageContent.innerHTML=`<div class="eyebrow">QUICK REVIEW · ACTIVE RECALL</div><h1 class="page-title">Flashcards</h1><p class="subtitle">Try to recall the answer before tapping to reveal.</p><div class="flash-wrap"><div class="flash-card" data-action="reveal-card"><span class="q-tag">${esc(card.topic)}</span>${flash.revealed?`<div class="flash-answer" style="margin-top:20px">${esc(back)}</div>`:`<div class="question-text">${esc(front)}</div><span class="small">Tap card to reveal answer</span>`}</div>${flash.revealed?`<div class="flash-actions"><button class="secondary-btn" data-action="card-again">✕ Need review</button><button class="primary-btn" data-action="card-know">✓ I know this</button></div>`:""}<div class="card-counter">Card ${flash.index+1} of ${pool.length} · <button class="text-link" data-action="shuffle-cards">Shuffle cards</button></div></div>`}
function renderSettings(){pageContent.innerHTML=`<div class="eyebrow">STUDY APP SETTINGS</div><h1 class="page-title">Settings</h1><p class="subtitle">No account needed. Your study progress stays in this browser, and you can reset it whenever you like.</p><div class="panel" style="margin-top:20px;max-width:680px"><h3>Appearance</h3><div class="setting-row"><span>Color theme</span><button class="secondary-btn" data-action="toggle-theme">Switch to ${state.settings?.theme==="dark"?"light":"dark"} mode</button></div></div><div class="panel" style="margin-top:15px;max-width:680px"><h3>Study data on this device</h3><div class="setting-row"><span>Saved questions answered</span><b>${Object.keys(state.answered).length} / 100</b></div><div class="setting-row"><span>Saved quiz sessions</span><b>${state.scores.length}</b></div><div class="setting-row"><span>Saved mistakes</span><b>${state.mistakes.length}</b></div><div style="margin-top:17px"><button class="secondary-btn" data-action="export-data">Download my study data</button> <button class="ghost-btn" data-action="reset-data">Reset all progress</button></div><p style="margin:15px 0 0;font-size:10px;color:#94979a">Reset clears saved answers, scores, mistakes, flashcard status, and streak from this browser.</p></div>`}
function toast(msg){const el=document.getElementById("toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}

document.addEventListener("click",e=>{const target=e.target.closest("button,[data-action],[data-topic]");if(!target)return;if(target.dataset.page){e.preventDefault();quiz=null;setPage(target.dataset.page);return}if(target.dataset.topic&&target.classList.contains("topic-card")){activePage="practice";renderSetup("practice");setTimeout(()=>{const sel=document.getElementById("quiz-topic");if(sel)sel.value=target.dataset.topic},0);return}if(target.dataset.count){document.querySelectorAll(".chip").forEach(c=>c.classList.toggle("selected",c===target));return}const action=target.dataset.action;if(!action)return;switch(action){case"toggle-theme":toggleTheme();break;case"start-quiz":startQuiz(target.dataset.mode);break;case"answer":checkAnswer(target.dataset.answer);break;case"check-text":checkAnswer(document.getElementById("short-answer")?.value);break;case"next-question":quiz.index++;quiz.selected=null;quiz.checked=false;renderQuiz();break;case"check-matching":checkMatching();break;case"next-matching":quiz.index+=quiz.matchingRounds[quiz.round].length;quiz.round++;quiz.checked=false;renderQuiz();break;case"exit-quiz":quiz=null;renderPage();break;case"practice-mistakes":if(!state.mistakes.length){toast("There are no saved mistakes yet.");break}startQuiz("practice",true);break;case"practice-topic":activePage="practice";renderSetup("practice");setTimeout(()=>{const sel=document.getElementById("quiz-topic");if(sel)sel.value=target.dataset.topic},0);break;case"reveal-card":flash.revealed=!flash.revealed;renderFlashcards();break;case"card-again":flash.revealed=false;flash.index=(flash.index+1)%flash.items.length;renderFlashcards();break;case"card-know":flash.revealed=false;state.flashcards[flash.items[flash.index].id]="known";saveState();flash.index=(flash.index+1)%flash.items.length;renderFlashcards();break;case"shuffle-cards":flash.items=shuffled(qbank);flash.index=0;flash.revealed=false;renderFlashcards();break;case"export-data":downloadData();break;case"reset-data":if(confirm("Clear all saved scores, mistakes, and progress from this browser?")){const theme=state.settings?.theme;state=freshState();if(theme)state.settings.theme=theme;saveState();renderPage();toast("Study progress cleared.")}break}});
document.getElementById("mobile-menu").addEventListener("click",()=>document.getElementById("sidebar").classList.toggle("open"));
document.addEventListener("keydown",e=>{if(e.key==="Enter"&&e.target.id==="short-answer"&&!e.shiftKey){e.preventDefault();document.querySelector('[data-action="check-text"]')?.click()}});
function downloadData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),questionBank:qbank.map(({id,category,topic,prompt,kind,choices,answer,explanation,difficulty})=>({id,category,topic,question:prompt,questionType:kind,choices,correctAnswer:answer,explanation,difficulty})),progress:state},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="greeklit-study-data.json";a.click();URL.revokeObjectURL(a.href)}
function validateBank(){const counts={};qbank.forEach(q=>{const k=categoryFor(q);counts[k]=(counts[k]||0)+1});const ids=new Set(qbank.map(q=>q.id));if(qbank.length!==100||Object.keys(EXPECTED).some(k=>counts[k]!==EXPECTED[k])||ids.size!==100)console.error("Question bank validation failed",qbank.length,counts,ids.size);else console.info("Question bank verified: exactly 100 unique questions",counts)}
validateBank();applyTheme();updateMistakeBadge();document.getElementById("streak-number").textContent=`${state.streak||0} day streak`;setPage("dashboard");
